// Từ điển thuật ngữ theo chuyên ngành (EN -> VI).
// Dùng cho bộ dịch miễn phí: "khoá" thuật ngữ trước khi dịch rồi thay lại đúng từ.
// Với bộ dịch LLM: tên ngành được đưa thẳng vào câu lệnh dịch.
// Có thể bổ sung thoải mái. Khoá là regex-an-toàn (đã escape sẵn khi dùng \\b...\\b).

export const DOMAIN_LABELS = {
  general: "Tổng quát",
  kythuat: "Kỹ thuật chung",
  me: "Cơ điện (M&E / HVAC)",
  xaydung: "Xây dựng",
  cokhi: "Cơ khí",
  dien: "Điện",
  cntt: "CNTT / Phần mềm",
  oto: "Ô tô",
  hoachat: "Hoá chất / Quy trình",
  amthuc: "Ẩm thực / Nhà bếp",
  dulich: "Du lịch / Khách sạn",
  vanphong: "Kinh doanh / Công sở",
  giaoduc: "Giáo dục",
  vanhoc: "Văn học / Truyện",
  yte: "Y tế",
  phaply: "Pháp lý / Hợp đồng",
};

// Câu mô tả ngành cho LLM.
export const DOMAIN_PROMPT = {
  general: "",
  kythuat: "kỹ thuật và tài liệu kỹ thuật nói chung",
  me: "cơ điện công trình (M&E), thông gió và điều hoà không khí (HVAC)",
  xaydung: "xây dựng và kết cấu công trình",
  cokhi: "cơ khí chế tạo",
  dien: "kỹ thuật điện và tự động hoá",
  cntt: "công nghệ thông tin và phát triển phần mềm",
  oto: "kỹ thuật ô tô",
  hoachat: "công nghệ hoá học và kỹ thuật quy trình",
  amthuc: "ẩm thực, chế biến món ăn và vận hành nhà bếp",
  dulich: "du lịch, lữ hành và nghiệp vụ khách sạn",
  vanphong: "kinh doanh, quản trị và văn bản công sở",
  giaoduc: "giáo dục và đào tạo",
  vanhoc: "văn học (dịch văn phong tự nhiên, giữ giọng điệu)",
  yte: "y khoa và chăm sóc sức khoẻ",
  phaply: "pháp lý và hợp đồng",
};

const G = {
  kythuat: {
    "specification": "quy cách kỹ thuật",
    "specifications": "quy cách kỹ thuật",
    "tolerance": "dung sai",
    "clearance": "khe hở",
    "assembly": "cụm lắp ráp",
    "bracket": "giá đỡ",
    "fastener": "chi tiết kẹp chặt",
    "gasket": "gioăng",
    "housing": "vỏ / thân máy",
    "shaft": "trục",
    "bearing": "ổ bi / bạc đạn",
    "torque": "mô-men xoắn",
    "load": "tải trọng",
    "rated": "định mức",
    "commissioning": "chạy thử nghiệm thu",
    "maintenance": "bảo trì",
    "calibration": "hiệu chuẩn",
    "datasheet": "phiếu thông số kỹ thuật",
    "actuator": "cơ cấu chấp hành",
    "sensor": "cảm biến",
    "gauge": "đồng hồ đo",
  },
  me: {
    "air handling unit": "bộ xử lý không khí (AHU)",
    "AHU": "AHU",
    "fan coil unit": "dàn lạnh FCU",
    "FCU": "FCU",
    "damper": "van gió",
    "fire damper": "van gió chặn lửa",
    "volume control damper": "van điều chỉnh lưu lượng gió",
    "VCD": "van điều chỉnh lưu lượng (VCD)",
    "ductwork": "hệ thống ống gió",
    "duct": "ống gió",
    "diffuser": "miệng gió khuếch tán",
    "grille": "cửa gió",
    "louvre": "cửa chớp lấy gió",
    "louver": "cửa chớp lấy gió",
    "plenum": "hộp gió",
    "supply air": "gió cấp",
    "return air": "gió hồi",
    "exhaust air": "gió thải",
    "outdoor air": "gió tươi",
    "fresh air": "gió tươi",
    "make-up air": "gió bù",
    "makeup air": "gió bù",
    "air change rate": "bội số trao đổi không khí",
    "static pressure": "áp suất tĩnh",
    "chiller": "máy làm lạnh (chiller)",
    "cooling tower": "tháp giải nhiệt",
    "condenser": "dàn ngưng",
    "evaporator": "dàn bay hơi",
    "refrigerant": "môi chất lạnh",
    "chilled water": "nước lạnh",
    "condenser water": "nước giải nhiệt",
    "pump": "bơm",
    "variable air volume": "lưu lượng gió thay đổi (VAV)",
    "VAV": "VAV",
    "air terminal": "thiết bị đầu cuối gió",
    "terminal unit": "bộ đầu cuối",
    "ventilation": "thông gió",
    "mechanical ventilation": "thông gió cơ khí",
    "natural ventilation": "thông gió tự nhiên",
    "smoke exhaust": "hút khói",
    "pressurization": "tạo áp",
    "occupancy": "mật độ người sử dụng",
    "flow rate": "lưu lượng",
    "duct velocity": "vận tốc gió trong ống",
    "insulation": "cách nhiệt",
    "thermal insulation": "cách nhiệt",
  },
  xaydung: {
    "reinforcement": "cốt thép",
    "rebar": "thép thanh",
    "formwork": "ván khuôn",
    "shoring": "chống đỡ tạm",
    "slab": "sàn / bản",
    "beam": "dầm",
    "column": "cột",
    "footing": "móng đơn",
    "foundation": "móng",
    "load-bearing wall": "tường chịu lực",
    "shear wall": "vách cứng",
    "precast": "đúc sẵn",
    "cast-in-situ": "đổ tại chỗ",
    "screed": "lớp vữa cán nền",
    "waterproofing": "chống thấm",
    "expansion joint": "khe co giãn",
    "aggregate": "cốt liệu",
    "curing": "bảo dưỡng bê tông",
    "compressive strength": "cường độ chịu nén",
    "settlement": "lún",
  },
  cokhi: {
    "lathe": "máy tiện",
    "milling machine": "máy phay",
    "weld": "mối hàn",
    "welding": "hàn",
    "fillet weld": "mối hàn góc",
    "machining": "gia công cắt gọt",
    "fixture": "đồ gá",
    "spindle": "trục chính",
    "feed rate": "tốc độ tiến dao",
    "coolant": "dung dịch làm mát",
    "surface finish": "độ nhám bề mặt",
    "runout": "độ đảo",
    "keyway": "rãnh then",
    "spline": "then hoa",
    "coupling": "khớp nối",
    "flange": "mặt bích",
    "bushing": "bạc lót",
    "hydraulic": "thuỷ lực",
    "pneumatic": "khí nén",
    "backlash": "khe hở ăn khớp",
  },
  dien: {
    "circuit breaker": "cầu dao / aptomat",
    "busbar": "thanh cái",
    "switchgear": "tủ đóng cắt",
    "switchboard": "tủ điện phân phối",
    "distribution board": "tủ điện tầng",
    "earthing": "nối đất",
    "grounding": "nối đất",
    "bonding": "liên kết đẳng thế",
    "conduit": "ống luồn dây",
    "cable tray": "máng cáp",
    "busway": "busway",
    "transformer": "máy biến áp",
    "rated current": "dòng điện định mức",
    "short circuit": "ngắn mạch",
    "overcurrent": "quá dòng",
    "residual current device": "thiết bị chống dòng rò (RCD)",
    "RCD": "RCD",
    "power factor": "hệ số công suất",
    "load shedding": "sa thải phụ tải",
    "single line diagram": "sơ đồ một sợi",
  },
  cntt: {
    "deployment": "triển khai",
    "repository": "kho mã nguồn",
    "commit": "commit",
    "pull request": "pull request",
    "endpoint": "điểm cuối API",
    "payload": "dữ liệu gửi kèm",
    "cache": "bộ nhớ đệm",
    "throughput": "thông lượng",
    "latency": "độ trễ",
    "load balancer": "bộ cân bằng tải",
    "middleware": "phần mềm trung gian",
    "authentication": "xác thực",
    "authorization": "phân quyền",
    "rate limit": "giới hạn tần suất",
    "rollback": "khôi phục phiên bản",
  },
  oto: {
    "camshaft": "trục cam",
    "crankshaft": "trục khuỷu",
    "throttle": "bướm ga",
    "torque converter": "biến mô",
    "differential": "bộ vi sai",
    "suspension": "hệ thống treo",
    "brake caliper": "cùm phanh",
    "manifold": "cổ góp",
    "coolant": "nước làm mát",
    "ECU": "bộ điều khiển điện tử (ECU)",
  },
  hoachat: {
    "feedstock": "nguyên liệu đầu vào",
    "reactor": "thiết bị phản ứng",
    "distillation": "chưng cất",
    "reflux": "hồi lưu",
    "heat exchanger": "thiết bị trao đổi nhiệt",
    "flow rate": "lưu lượng",
    "batch": "mẻ",
    "yield": "hiệu suất",
    "slurry": "huyền phù",
    "vessel": "bình / thiết bị chứa",
  },
  amthuc: {
    "sear": "áp chảo",
    "simmer": "ninh nhỏ lửa",
    "blanch": "chần",
    "fold": "trộn nhẹ tay",
    "proof": "ủ bột",
    "render": "thắng mỡ",
    "deglaze": "tráng chảo lấy nước cốt",
    "julienne": "thái sợi",
    "stock": "nước dùng",
  },
  dulich: {
    "check-in": "nhận phòng",
    "check-out": "trả phòng",
    "front desk": "quầy lễ tân",
    "housekeeping": "bộ phận buồng phòng",
    "concierge": "hỗ trợ khách",
    "amenities": "tiện nghi phòng",
    "itinerary": "lịch trình",
    "occupancy rate": "công suất phòng",
    "walk-in": "khách vãng lai",
  },
  vanphong: {
    "stakeholder": "bên liên quan",
    "deliverable": "sản phẩm bàn giao",
    "milestone": "cột mốc",
    "scope": "phạm vi công việc",
    "onboarding": "hội nhập nhân viên mới",
    "headcount": "số lượng nhân sự",
    "quarter": "quý",
    "invoice": "hoá đơn",
    "purchase order": "đơn đặt hàng",
  },
  giaoduc: {
    "syllabus": "đề cương môn học",
    "assessment": "đánh giá",
    "rubric": "thang chấm điểm",
    "scaffolding": "hỗ trợ học tập theo bậc",
    "formative assessment": "đánh giá quá trình",
    "learning outcome": "chuẩn đầu ra",
  },
  yte: {
    "dosage": "liều dùng",
    "adverse effect": "tác dụng phụ",
    "contraindication": "chống chỉ định",
    "prognosis": "tiên lượng",
    "acute": "cấp tính",
    "chronic": "mạn tính",
    "in vitro": "in vitro",
  },
  phaply: {
    "hereinafter": "sau đây gọi là",
    "indemnify": "bồi hoàn",
    "liability": "trách nhiệm pháp lý",
    "breach": "vi phạm",
    "warranty": "bảo đảm",
    "governing law": "luật điều chỉnh",
    "force majeure": "bất khả kháng",
    "termination": "chấm dứt hợp đồng",
  },
  vanhoc: {},
};

// Trả về mảng [en, vi] đã sắp xếp cụm dài trước (để khớp "air handling unit" trước "air").
export function glossaryFor(domain) {
  const g = G[domain];
  if (!g) return null;
  return Object.entries(g).sort((a, b) => b[0].length - a[0].length);
}
